entryScript: score.py
runtime: python
condaFile: config/inference-conda.yml
extraDockerfileSteps:
schemaFile:
sourceDirectory: .
enableGpu: False
baseImage: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
baseImageRegistry:
