name: diabetes-inference-env
dependencies:
  - scikit-learn
  - python=3.8.13
  - pip=20.2.4
  - numpy
  - pip:
      - azureml-sdk
      - azureml-widgets
      - azureml-defaults
      - 'inference-schema[numpy-support]'
      - docker<5.0.0
      - PySocks==1.7.1
      - msal-extensions==0.3.1
      - urllib3==1.26.9