name: diabetes-training-env
dependencies:
  - scikit-learn
  - python=3.8.10
  - pip=20.2.4
  - numpy
  - pip:
      - azureml-sdk
      - azureml-widgets
      - azureml-defaults
      - 'inference-schema[numpy-support]'
      - docker<5.0.0 # this is the fix needed
      - PySocks==1.7.1
      - msal-extensions==0.3.1