name: diabetes-training-env
dependencies:
  - scikit-learn
  - python=3.8.10
  - pip=20.2.4
  - numpy
  - pip:
      - azureml-sdk
      - azureml-widgets
      - azureml-defaults
      - 'inference-schema[numpy-support]'