name: diabetes-training-env
dependencies:
- python=3.10.4
- pip=22.1.2
- numpy
- pip:
  - azureml-sdk
  - azureml-widgets
  - azureml-defaults
  - scikit-learn==0.21.3
  - inference-schema[numpy-support]
